const CONFIG={RAZORPAY_KEY_ID:"",ORG_NAME:"TMPCL",PHONE:"+91 70000 12345",EMAIL:"info@tmpcl.com"};
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const load=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
function toast(msg){let t=$('.toast')||document.body.appendChild(Object.assign(document.createElement('div'),{className:'toast'}));t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',3000)}
function initNav(){const h=$('.hamb'),n=$('.nav');if(h&&n)h.onclick=()=>n.classList.toggle('open');$$('.nav a,.mobile-bottom a').forEach(a=>{if(a.getAttribute('href')===location.pathname.split('/').pop()||(!location.pathname.split('/').pop()&&a.getAttribute('href')==='index.html'))a.classList.add('active')})}
function seed(){if(!localStorage.tmpclNews)store('tmpclNews',[{title:'TMPCL Player Trials Kick Off Across MP',cat:'Trials',date:'18 May 2026',body:'Player trials begin across Madhya Pradesh. Register now and showcase your talent.'},{title:'District Roadshows Create Massive Buzz',cat:'Selection',date:'15 May 2026',body:'TMPCL roadshows receive huge response from local players and cricket fans.'},{title:'Registration Counter Crosses 12,000',cat:'Update',date:'10 May 2026',body:'TMPCL registration response is growing strongly across districts.'}]);if(!localStorage.tmpclPartners)store('tmpclPartners',['SG','NIVIA','TYKA','Fancode','Sports Arena','Campa']);if(!localStorage.tmpclGallery)store('tmpclGallery',['Match Action','Team Moment','Trophy Ceremony','Trial Ground','Highlights','Team Huddle']);}
function ageFromDob(d){if(!d)return null;const dob=new Date(d),today=new Date();let a=today.getFullYear()-dob.getFullYear();const m=today.getMonth()-dob.getMonth();if(m<0||(m===0&&today.getDate()<dob.getDate()))a--;return a}
function regId(){let n=+(localStorage.tmpclRegSeq||0)+1;localStorage.tmpclRegSeq=n;return 'TMPCL-'+new Date().getFullYear()+'-'+String(n).padStart(5,'0')}
function renderDynamic(){const players=load('tmpclRegs',[]),news=load('tmpclNews',[]),partners=load('tmpclPartners',[]),gallery=load('tmpclGallery',[]);$$('[data-today]').forEach(e=>e.textContent=players.filter(p=>p.date===new Date().toLocaleDateString()).length||1247);$$('[data-total]').forEach(e=>e.textContent=players.length||12856);const nl=$('[data-news-list]');if(nl)nl.innerHTML=news.map(n=>`<article class="news-item"><small>${n.date} • ${n.cat}</small><h3>${n.title}</h3><p>${n.body}</p><a class="green">Read More →</a></article>`).join('');const pl=$('[data-partners]');if(pl)pl.innerHTML=partners.map(p=>`<b>${p}</b>`).join('');const gl=$('[data-gallery]');if(gl)gl.innerHTML=gallery.map((g,i)=>`<div class="thumb">${g}${i%3===0?' ▶':''}</div>`).join('')}
function initRegistration(){const form=$('#registrationForm');if(!form)return;const role=$('#role'),amount=$('#amount'),pay=$('#payBtn'),grade=$('#grade'),dob=$('#dob');function fee(){let v=role.value==='All-Rounder'?1299:999;amount.textContent='₹'+v;pay.textContent='Pay ₹'+v+' & Register';return v}role.onchange=fee;fee();$$('.fee-card').forEach(c=>c.onclick=()=>{role.value=c.dataset.role;$$('.fee-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');fee()});grade.onchange=()=>{if(grade.value==='D'){const age=ageFromDob(dob.value);if(age!==null&&age>=19){grade.value='';toast('D Category only U19 players ke liye hai.')}}};pay.onclick=async e=>{e.preventDefault();if(!form.reportValidity())return;const age=ageFromDob(dob.value);if(grade.value==='D'&&(age===null||age>=19)){toast('D Category ke liye DOB se age Under-19 honi chahiye.');return}const data=Object.fromEntries(new FormData(form).entries());data.age=age;data.amount=fee();data.id=regId();data.date=new Date().toLocaleDateString();data.status=CONFIG.RAZORPAY_KEY_ID?'Payment Started':'Razorpay Key Required';data.paymentId='';
if(!CONFIG.RAZORPAY_KEY_ID){saveReg(data);$('#successId').textContent=data.id;$('.success-box').style.display='block';toast('Registration saved. Razorpay Key ID script.js me add karne par live payment open hoga.');return}
loadRazorpay(()=>{const rz=new Razorpay({key:CONFIG.RAZORPAY_KEY_ID,amount:data.amount*100,currency:'INR',name:'TMPCL',description:data.role+' Trial Registration',handler:function(res){data.status='Paid';data.paymentId=res.razorpay_payment_id||'';saveReg(data);$('#successId').textContent=data.id;$('.success-box').style.display='block';toast('Payment successful. Registration confirmed.');},prefill:{name:data.fullName,email:data.email,contact:data.mobile},theme:{color:'#b7ff18'}});rz.open();});}}
function saveReg(data){const all=load('tmpclRegs',[]);all.unshift(data);store('tmpclRegs',all)}
function loadRazorpay(cb){if(window.Razorpay)return cb();const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=cb;s.onerror=()=>toast('Razorpay script load nahi hua. Internet check karein.');document.body.appendChild(s)}
function initContact(){const f=$('#contactForm');if(f)f.onsubmit=e=>{e.preventDefault();const all=load('tmpclContacts',[]);all.unshift({...Object.fromEntries(new FormData(f).entries()),date:new Date().toLocaleString()});store('tmpclContacts',all);f.reset();toast('Message saved. Admin panel me dikh jayega.')}}
function initAdmin(){const login=$('#adminLogin'),dash=$('#adminDash');if(!login)return;function showDash(){login.classList.add('hide');dash.classList.remove('hide');renderAdmin('regs')}if(sessionStorage.tmpclAdmin==='yes')showDash();login.onsubmit=e=>{e.preventDefault();const u=$('#adminUser').value,p=$('#adminPass').value;if(u==='admin'&&p==='admin123'){sessionStorage.tmpclAdmin='yes';showDash()}else toast('Login: admin / admin123 use karein')};$$('[data-tab]').forEach(b=>b.onclick=()=>renderAdmin(b.dataset.tab));}
function renderAdmin(tab){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const box=$('#adminContent');const regs=load('tmpclRegs',[]),news=load('tmpclNews',[]),contacts=load('tmpclContacts',[]),partners=load('tmpclPartners',[]),gallery=load('tmpclGallery',[]);if(tab==='regs')box.innerHTML=`<h2>Player Registrations</h2><p class="note">Total: ${regs.length}</p><table><tr><th>ID</th><th>Name</th><th>Role</th><th>Grade</th><th>Amount</th><th>Status</th><th>Payment ID</th></tr>${regs.map(r=>`<tr><td>${r.id}</td><td>${r.fullName}</td><td>${r.role}</td><td>${r.grade}</td><td>₹${r.amount}</td><td><span class="badge">${r.status}</span></td><td>${r.paymentId||'-'}</td></tr>`).join('')}</table>`;if(tab==='teams')box.innerHTML=`<h2>Team Structure</h2><div class="structure-grid"><div><b>A</b><span>5 Players</span></div><div><b>B</b><span>5 Players</span></div><div><b>C</b><span>5 Players</span></div><div><b>D</b><span>3 U19 Players</span></div></div><p class="note">Total 18 players per team. D Category only U19.</p>`;if(tab==='news')box.innerHTML=`<h2>Manage News</h2><form id="addNews" class="grid three"><input name="title" placeholder="News title" required><input name="cat" placeholder="Category" required><input name="date" placeholder="Date" required><textarea name="body" placeholder="Short update" required></textarea><button class="btn">Add News</button></form><div class="news-cards">${news.map(n=>`<article><small>${n.date}</small><h3>${n.title}</h3><p>${n.body}</p></article>`).join('')}</div>`;if($('#addNews'))$('#addNews').onsubmit=e=>{e.preventDefault();news.unshift(Object.fromEntries(new FormData(e.target).entries()));store('tmpclNews',news);renderAdmin('news')};if(tab==='gallery')box.innerHTML=`<h2>Manage Gallery</h2><form id="addGallery" class="grid two"><input name="title" placeholder="Gallery item title" required><button class="btn">Add Gallery Item</button></form><div class="gallery-grid">${gallery.map(g=>`<div>${g}</div>`).join('')}</div>`;if($('#addGallery'))$('#addGallery').onsubmit=e=>{e.preventDefault();gallery.unshift(new FormData(e.target).get('title'));store('tmpclGallery',gallery);renderAdmin('gallery')};if(tab==='partners')box.innerHTML=`<h2>Manage Partners</h2><form id="addPartner" class="grid two"><input name="name" placeholder="Partner name" required><button class="btn">Add Partner</button></form><div class="logos">${partners.map(p=>`<b>${p}</b>`).join('')}</div>`;if($('#addPartner'))$('#addPartner').onsubmit=e=>{e.preventDefault();partners.unshift(new FormData(e.target).get('name'));store('tmpclPartners',partners);renderAdmin('partners')};if(tab==='contacts')box.innerHTML=`<h2>Contact Messages</h2><table><tr><th>Name</th><th>Mobile</th><th>Subject</th><th>Message</th></tr>${contacts.map(c=>`<tr><td>${c.name}</td><td>${c.mobile}</td><td>${c.subject}</td><td>${c.message}</td></tr>`).join('')}</table>`;}
window.addEventListener('DOMContentLoaded',()=>{seed();initNav();renderDynamic();initRegistration();initContact();initAdmin()});
