const TMPCL={razorpayKeyId:""};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function store(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k,d=[]){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}
function uid(){const n=(load('tmpcl_registrations',[]).length+1).toString().padStart(4,'0');return 'TMPCL-2026-'+n}
function ageFromDob(dob){if(!dob)return 0;const d=new Date(dob);const t=new Date();let a=t.getFullYear()-d.getFullYear();const m=t.getMonth()-d.getMonth();if(m<0||(m===0&&t.getDate()<d.getDate()))a--;return a}
function initNav(){const h=$('.hamb'),links=$('.links');h&&h.addEventListener('click',()=>links.classList.toggle('open'));const page=document.body.dataset.page;$$('[data-nav]').forEach(a=>{if(a.dataset.nav===page)a.classList.add('active')});$$('.bottom-nav a').forEach(a=>{if(a.dataset.nav===page)a.classList.add('active')});}
function seed(){if(!localStorage.getItem('tmpcl_news'))store('tmpcl_news',[{title:'TMPCL player trials registration open',cat:'Trials',date:'2026-06-01',text:'Players can register online and choose role/category.'},{title:'Team structure finalized: A5 B5 C5 D3',cat:'Teams',date:'2026-06-02',text:'Every team will have 18 players with 3 U19 players in D category.'}]);if(!localStorage.getItem('tmpcl_gallery'))store('tmpcl_gallery',[{title:'Trial preparation',type:'Photo',url:'gallery-preview.png'},{title:'Team structure preview',type:'Photo',url:'teams-preview.png'}]);if(!localStorage.getItem('tmpcl_partners'))store('tmpcl_partners',[{name:'Title Sponsor',type:'Title Sponsor'},{name:'Kit Partner',type:'Official Kit Partner'},{name:'Media Partner',type:'Official Media Partner'}]);}
function initCounters(){const regs=load('tmpcl_registrations',[]);const today=new Date().toISOString().slice(0,10);const todayCount=regs.filter(r=>(r.created||'').slice(0,10)===today).length;$$('[data-count="today"]').forEach(e=>e.textContent=todayCount+87);$$('[data-count="total"]').forEach(e=>e.textContent=regs.length+1247);$$('[data-count="districts"]').forEach(e=>e.textContent='52');}
function feeFor(role){return role==='All-Rounder'?1299:999}
function initRegistration(){const form=$('#registrationForm');if(!form)return;const role=$('#role'),fee=$('#fee'),cat=$('#category'),dob=$('#dob'),age=$('#age'),summary=$('#paySummary');function refresh(){const amount=feeFor(role.value);fee.value='₹'+amount;summary.textContent='Pay ₹'+amount+' securely with Razorpay';if(dob.value)age.value=ageFromDob(dob.value);if(cat.value==='D'&&ageFromDob(dob.value)>=19){cat.setCustomValidity('D category only U19 players ke liye hai');}else cat.setCustomValidity('');}['change','input'].forEach(ev=>{role.addEventListener(ev,refresh);cat.addEventListener(ev,refresh);dob.addEventListener(ev,refresh)});refresh();form.addEventListener('submit',async e=>{e.preventDefault();refresh();if(!form.checkValidity()){form.reportValidity();return}const amount=feeFor(role.value);const data=Object.fromEntries(new FormData(form).entries());data.amount=amount;data.fee='₹'+amount;data.registrationId=uid();data.status=TMPCL.razorpayKeyId?'Payment Initiated':'Pending Razorpay Setup';data.created=new Date().toISOString();data.age=ageFromDob(data.dob);const saveReg=(paymentId='')=>{data.razorpayPaymentId=paymentId;data.status=paymentId?'Paid':'Saved - Payment Pending';const regs=load('tmpcl_registrations',[]);regs.push(data);store('tmpcl_registrations',regs);$('#successBox').style.display='block';$('#successText').innerHTML=`Registration saved successfully.<br><b>${data.registrationId}</b><br>Status: ${data.status}`;form.reset();refresh();initCounters();};if(TMPCL.razorpayKeyId&&window.Razorpay){const options={key:TMPCL.razorpayKeyId,amount:amount*100,currency:'INR',name:'TMPCL',description:data.role+' Registration',image:'tmpcl-logo.png',handler:function(res){saveReg(res.razorpay_payment_id)},prefill:{name:data.name,contact:data.mobile,email:data.email||''},theme:{color:'#a6ff35'}};new Razorpay(options).open();}else{saveReg('');}})}
function renderNews(){const box=$('#newsList');if(!box)return;box.innerHTML=load('tmpcl_news',[]).map(n=>`<article class="card news-card"><img src="news-preview.png" alt="news"><div><span class="tag">${n.cat||'Update'}</span><h3>${n.title}</h3><p>${n.text||''}</p><small class="muted">${n.date||''}</small></div></article>`).join('')}
function renderGallery(){const box=$('#galleryList');if(!box)return;box.innerHTML=load('tmpcl_gallery',[]).map(g=>`<div class="card"><img class="showcase-img" src="${g.url||'gallery-preview.png'}" alt="gallery"><h3>${g.title}</h3><span class="tag">${g.type||'Photo'}</span></div>`).join('')}
function renderPartners(){const box=$('#partnerList');if(!box)return;box.innerHTML=load('tmpcl_partners',[]).map(p=>`<div class="partner-logo">${p.name}</div>`).join('')}
function initContact(){const form=$('#contactForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());data.created=new Date().toISOString();const arr=load('tmpcl_messages',[]);arr.push(data);store('tmpcl_messages',arr);alert('Message saved. TMPCL team will contact you.');form.reset();})}
function initAdmin(){const login=$('#adminLogin'),shell=$('#adminShell');if(!login)return;const show=()=>{login.style.display='none';shell.style.display='block';renderAdmin()};if(sessionStorage.getItem('tmpcl_admin')==='yes')show();login.addEventListener('submit',e=>{e.preventDefault();const u=$('#adminUser').value.trim(),p=$('#adminPass').value.trim();if(u==='admin'&&p==='admin123'){sessionStorage.setItem('tmpcl_admin','yes');show()}else alert('Wrong username or password')});$('#logoutBtn')?.addEventListener('click',()=>{sessionStorage.removeItem('tmpcl_admin');location.reload()});$$('[data-admin-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const type=f.dataset.adminForm;const data=Object.fromEntries(new FormData(f).entries());const map={news:'tmpcl_news',gallery:'tmpcl_gallery',partners:'tmpcl_partners'};const arr=load(map[type],[]);arr.unshift(data);store(map[type],arr);f.reset();renderAdmin();alert('Saved')}))}
function renderAdmin(){const regs=load('tmpcl_registrations',[]),msgs=load('tmpcl_messages',[]),news=load('tmpcl_news',[]),gal=load('tmpcl_gallery',[]);$('#adminStats').innerHTML=`<div class="stat"><strong>${regs.length}</strong><span>Total Registrations</span></div><div class="stat"><strong>${regs.filter(r=>r.status==='Paid').length}</strong><span>Paid</span></div><div class="stat"><strong>${msgs.length}</strong><span>Messages</span></div><div class="stat"><strong>${news.length+gal.length}</strong><span>Content Items</span></div>`;$('#regTable').innerHTML=`<table class="table"><thead><tr><th>ID</th><th>Name</th><th>Mobile</th><th>Role</th><th>Category</th><th>Age</th><th>Fee</th><th>Status</th></tr></thead><tbody>${regs.map(r=>`<tr><td>${r.registrationId}</td><td>${r.name}</td><td>${r.mobile}</td><td>${r.role}</td><td><span class="badge">${r.category}</span></td><td>${r.age}</td><td>${r.fee}</td><td>${r.status}</td></tr>`).join('')||'<tr><td colspan="8">No registrations yet.</td></tr>'}</tbody></table>`;$('#msgTable').innerHTML=`<table class="table"><thead><tr><th>Name</th><th>Mobile</th><th>Subject</th><th>Message</th></tr></thead><tbody>${msgs.map(m=>`<tr><td>${m.name}</td><td>${m.mobile}</td><td>${m.subject}</td><td>${m.message}</td></tr>`).join('')||'<tr><td colspan="4">No messages.</td></tr>'}</tbody></table>`}
document.addEventListener('DOMContentLoaded',()=>{seed();initNav();initCounters();initRegistration();renderNews();renderGallery();renderPartners();initContact();initAdmin();});
